# Generated by Django 3.2.23 on 2024-02-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supported', '0004_delete_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamslist',
            name='team',
            field=models.CharField(choices=[('arsenal', 'Arsenal'), ('aston_villa', 'Aston Villa'), ('bournemouth', 'Bournemouth'), ('brentford', 'Brentford'), ('brighton', 'Brighton'), ('burnley', 'Burnley'), ('chelsea', 'Chelsea'), ('crystal_palace', 'Crystal Palace'), ('everton', 'Everton'), ('fulham', 'Fulham'), ('liverpool', 'Liverpool'), ('luton_town', 'Luton Town'), ('man_city', 'Man City'), ('man_utd', 'Man Utd'), ('newcastle', 'Newcastle'), ('notts_forest', 'Notts Forest'), ('sheff_utd', 'Sheff Utd'), ('tottenham', 'Tottenham'), ('west Ham', 'West Ham'), ('wolves', 'Wolves')], max_length=40, unique=True),
        ),
    ]
